# --- runtime ---
mode: paper
provider: alpaca_ws
discord_channel_id: 1411064822635696188  # set your target channel ID
timeframe: 5m   

# Risk & exits
risk:
  equity: 10000
  per_trade_r_pct: 0.01          # 1% risk per trade
  max_intrabar_loss_pct: 0.02    # emergency exit if price drops 2% from entry immediately

exits:
  take_profit_R: 0               # 0 = no fixed TP; we trail & exit on momentum flip
  trail_ema: 20                  # trailing stop via EMA20 of the working timeframe


momentum:
  doji_body_pct: 0.2
  macd_fast: 12
  macd_slow: 26
  macd_signal: 9
  cci_len: 14
  cci_entry: 0
  cci_exit: 0
  confirm_break_high: true
  use_patterns: ["doji","hammer","inverted_hammer","bullish_engulfing"]
  exit_patterns: ["shooting_star","bearish_engulfing"]